import { pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const inviteStatus = pgEnum("invite_status", [
  "pending",
  "accepted",
  "expired",
]);

export const user = pgTable("user", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const invite = pgTable("invite", {
  id: uuid("id").primaryKey().defaultRandom(),
  token: text("token").notNull().unique(),
  email: text("email").notNull(),
  status: inviteStatus("status").notNull().default("pending"),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const session = pgTable("session", {
  // The random ≥128-bit value stored in the session cookie — generated by
  // application code (00b/00c), not the database, so no defaultRandom() here.
  id: text("id").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => user.id),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const lead = pgTable("lead", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  // Only 'open' is used by seed data for this spike — narrowed at the type
  // level rather than a Postgres enum so widening it (00d+) is a pure type
  // change, not a migration.
  status: text("status").notNull().default("open").$type<"open">(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
